### ISSUE TITLE
Features we need to document (WIP)

### ISSUE THREAD

**Issue by ChristophLabacher** [atelierdisko/dsk#23]
* [x] Using `search:term` in local hyperlinks to enter "term" into the search on click
* [x] Using `Cmd + k` (or a better shortcut?) to focus the search
* [x] Ignored directories (`x_*`, `.*`, `node_modules`
* [x] Manual ordering of directories (`01_`)
* [x] Files that are not listed (readme, index, api)

**Comment by davidpersson** [comment]
* [ ] We need to clarify which markdown features we support through our blackfriday parser.

**Comment by davidpersson** [comment]
Fixed in 5132dcb4315854ded14965a75ffee0e1c07c10ea
and 9c327386d63a1a68721177b69a32d0f70f94d000. Frontend features are either obvious or should be documented inside the frontend itself. Instead of `search:term` links we now reconstruct the search term by looking at a links `?q=`. We use pretty standard markdown features, thus we don't need to document them now. If users aspect sth to work which doesn't we either activate that feature or document it then.
